// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdM4SYw5nnAyPXlNh6IittKWjj2xPXsxE',
    appId: '1:1023907057330:web:6c2d41b6d9ba88609643ab',
    messagingSenderId: '1023907057330',
    projectId: 'proyecto2025-9480b',
    authDomain: 'proyecto2025-9480b.firebaseapp.com',
    storageBucket: 'proyecto2025-9480b.firebasestorage.app',
    measurementId: 'G-132E77QWJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv5RD7pitvI7p3flh16J6f8HRvifGa870',
    appId: '1:1023907057330:android:fa3aa5bc1fc626ce9643ab',
    messagingSenderId: '1023907057330',
    projectId: 'proyecto2025-9480b',
    storageBucket: 'proyecto2025-9480b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl5JKDyFlnCGmi9hpg0xVV2O83QreoRXE',
    appId: '1:1023907057330:ios:31bcbd17198f0d8e9643ab',
    messagingSenderId: '1023907057330',
    projectId: 'proyecto2025-9480b',
    storageBucket: 'proyecto2025-9480b.firebasestorage.app',
    iosBundleId: 'com.yuravision.incuba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl5JKDyFlnCGmi9hpg0xVV2O83QreoRXE',
    appId: '1:1023907057330:ios:82a2d3d460e0054a9643ab',
    messagingSenderId: '1023907057330',
    projectId: 'proyecto2025-9480b',
    storageBucket: 'proyecto2025-9480b.firebasestorage.app',
    iosBundleId: 'com.example.yuravision01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdM4SYw5nnAyPXlNh6IittKWjj2xPXsxE',
    appId: '1:1023907057330:web:c3afb3155bd487699643ab',
    messagingSenderId: '1023907057330',
    projectId: 'proyecto2025-9480b',
    authDomain: 'proyecto2025-9480b.firebaseapp.com',
    storageBucket: 'proyecto2025-9480b.firebasestorage.app',
    measurementId: 'G-BJ2R5JXD07',
  );
}
